version: '3'
services:
  app:
    build: .
    volumes:
      - ./:/app
      - node_modules
    ports:
      - '8000:8000'

  db:
    image: redis:7.0-alpine
    restart: always
    ports:
      - '6379:6379'